#! /usr/bin/python
import cgi
import cgitb
cgitb.enable()

MAINENTRANCE = "Go to CUSTOMER WAITING AREA"
CUSTOMERWAITINGAREA = "Go to TELLER AREA, VAULT ACCESS, OFFICE AREA, ACCESS CORRIDOR, MAIN ENTRANCE"
TELLERAREA = "Go to VAULT ACCESS, CUSTOMER WAITING AREA"
OFFICEAREA = "Go to CUSTOMER WAITING AREA, ROOF ACCESS, "
ACCESS_CORRIDOR = "Go to VAULT ACCESS, CUSTOMER WAITING AREA"
MANAGERS_OFFICE = "Go to OFFICE AREA"
SECURITY_ROOM = "Go to ROOF ACCESS"
ROOF_ACCESS = "Go to ROOF"
VAULT_ACCESS = "Go to VAULT, CUSTOMER WAITING AREA, TELLER AREA"
VAULT = "Go to VAULT ACCESS"
PARKING_LOT = "Go to BACK ENTRANCE"
STAFF_ENTRANCE = "Go to VAULT ACCESS, CUSTOMER WAITING AREA"
BACK_ENTRANCE = "Go to ROOF ACCESS, SECURITY ROOM"
ROOF = "Go to ROOF ACCESS"
VAN = "Heist complete!"

